name: Docker Build & Push on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build the tagged Docker image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          docker build . --file Dockerfile --build-arg username=${{ secrets.USERNAME }} --build-arg token=${{ secrets.TOKEN }} --tag samagragovernance/inbound:$RELEASE_VERSION
      - name: Push the tagged Docker image
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: docker push samagragovernance/inbound:$RELEASE_VERSION

      # - uses: actions/checkout@v2
      # - name: Build container image
      #   run: docker build -t inbound .
      # - name: Launch container
      #   run: docker run -dp 8000:8080 --env-file env.sample inbound
      #   timeout-minutes: 5
      # - run: docker ps
      # - name: Wait for Service to start
      #   run: while ! curl -s localhost:8000/health; do sleep 1; done
      #   timeout-minutes: 1
      # - name: Check API health
      #   run: curl -s localhost:8000/health
